### ISSUE TITLE
手机号验证166号段验证不通过

### ISSUE THREAD

**Issue by langliu** [any86/any-rule#1]
https://baike.baidu.com/item/166/22068995?fr=aladdin
![image](https://user-images.githubusercontent.com/18554111/60149869-d4459100-9808-11e9-9a83-dc377a6eff67.png)

**Comment by any86** [comment]
十分感谢，在外面，一会回去就改

**Comment by any86** [comment]
改完喽, 多谢指正
![](http://ww1.sinaimg.cn/large/005IQkzXly1g4eqym9cdlj30sr06rglq.jpg)
