### ISSUE TITLE
idea插件中密码强度校验和web版的不一致，而且idea中的正则校验有问题

### ISSUE THREAD

**Issue by dking999** [any86/any-rule#102]
![图片](https://user-images.githubusercontent.com/34230179/82884894-fa266900-9f76-11ea-9868-7443956876ba.png)
![图片](https://user-images.githubusercontent.com/34230179/82884975-175b3780-9f77-11ea-89dd-13535cf3866e.png)

**Comment by any86** [comment]
idea版本并不是官方开发的哦(因为我不会idea的插件开发, 所以近期没有官方idea版本的计划), 是另一个同学开发的, 我帮他在我的仓库主页推广, 他的github issue地址是: https://github.com/zhoriya/idea-rule/issues/new
