### ISSUE TITLE
any-rule的Alfred Workflow版本

### ISSUE THREAD

**Issue by cccyb** [any86/any-rule#104]
感谢作者汇总了这么多使用的正则表达式，基于作者的数据，本人写了个简单的Alfred Workflow，如果有小伙伴不使用VsCode和IDEA的，又觉得Web在线查询麻烦的，同时又使用Mac安装了Alfred的小伙伴，可以试试我这个版本，使用起来也很方便，workflow地址：[https://github.com/cccyb/workflows](https://github.com/cccyb/workflows)

**Comment by any86** [comment]
感谢支持, 不过我不知道什么是Alfred Wordflows, 上次帮助做IDEA的同学推了, 后续他不维护, 全都来找我, 我还不会做IDEA插件, 我有点怕了, 你先研究下啥是Alfred Wordflows, 稍后我观察下帮你推广到首页

**Comment by any86** [comment]
我装了Alfred了, 请问如何安装你的插件

**Comment by cccyb** [comment]
> 我装了Alfred了, 请问如何安装你的插件

把插件下载下来后，直接双击就行了

**Comment by cccyb** [comment]
> 感谢支持, 不过我不知道什么是Alfred Wordflows, 上次帮助做IDEA的同学推了, 后续他不维护, 全都来找我, 我还不会做IDEA插件, 我有点怕了, 你先研究下啥是Alfred Wordflows, 稍后我观察下帮你推广到首页

Alfred Workflows就是Mac上很流行的效率提升小工具，具体是什么可以搜索一下，这个插件也不复杂，最简单且核心的查询功能我已经写好了，其他小功能我也基本加好了，如果后续你有新增其他功能，我有空会继续维护的~

**Comment by any86** [comment]
我双击了, 让我指定运行程序, Alfred Wordflows是灰色的选不了呢

**Comment by cccyb** [comment]
> 我双击了, 让我指定运行程序, Alfred Wordflows是灰色的选不了呢

貌似workflow功能是要收费的，可能需要破解一下才能使用。。。

**Comment by any86** [comment]
已经放到首页了
![image](https://user-images.githubusercontent.com/8264787/84216937-72576780-aafd-11ea-91ef-9719fc9161c8.png)
