### ISSUE TITLE
我有更好的正则: 身份证号(2代,18位数字),最后一位是校验位,可能为数字或字符X

### ISSUE THREAD

**Issue by zengyuanchen** [any86/any-rule#106]
/^[1-9]\d{5}(?:18|19|20)\d{2}(?:0[1-9]|10|11|12)(?:0[1-9]|[1-2]\d|30|31)\d{3}[\dXx]$/

月份 由 0\d 改成0[1-9]

因为月份没有00月

**Comment by any86** [comment]
已修复, 感谢反馈
