### ISSUE TITLE
能否增加经度纬度的正则？

### ISSUE THREAD

**Issue by masterlirui** [any86/any-rule#109]
目前能找到的正则格式都不能校验到某种格式，如下：
经度：108.22.2.2.2.2.2.3.2.2.2 
类似于这种格式出现多个"."，没办法过滤掉，依然是正常的
纬度问题同上！

**Comment by any86** [comment]
经纬度有这么多"."吗? 这个叫做什么标准?

**Comment by masterlirui** [comment]
108.22.2.2.2.2.2.3.2.2.2 这样的格式是不合法的。
目前找到的正则表达式  是可以让这样的格式通过的
我期待的是不让他通过这样的格式
找到的其中之一的经度正则为：
/^(-|\+)?(((\d|[1-9]\d|1[0-7]\d|0{1,3})\.\d{0,6})|(\d|[1-9]\d|1[0-7]\d|0{1,3})|180\.0{0,6}|180)$/

**Comment by any86** [comment]
我也没找到具体的规则, 我观察学术上表示是这样**113°12'39.6"**. 而一般程序中都用小数表示,  而且对小数位数没有长度限制.
至于这个范围, 我看是有从东经180度~西经180度, 但是不知道可以不以用-180~180这么表示, 我再确定下, 你要是了解就帮我确认下.
