### ISSUE TITLE
我有更好的正则: 车牌号(新能源)

### ISSUE THREAD

**Issue by dyb881** [any86/any-rule#115]
/^[京津沪渝冀豫云辽黑湘皖鲁新苏浙赣鄂桂甘晋蒙陕吉闽贵粤青藏川宁琼使领]{1}[A-HJ-NP-Z]{1}(([0-9]{5}[DF])|([DF][A-HJ-NP-Z0-9][0-9]{4}))$/

**Comment by any86** [comment]
已修复, 感谢
