### ISSUE TITLE
你好，大佬

### ISSUE THREAD

**Issue by zdd-jgt** [any86/any-rule#12]
有国外手机号的正则判断吗

**Comment by any86** [comment]
暂时么有啊 , 我研究下补上

> 有国外手机号的正则判断吗

**Comment by any86** [comment]
> 有国外手机号的正则判断吗

比如哪个国家?

**Comment by zdd-jgt** [comment]
感谢您的回复，目前我需要的是印尼这个方面的

**Comment by zdd-jgt** [comment]
我自己查找没找到结果，主要是没找到他们手机号的是什么样的，网上的人说有的是12位的0开头，有的是11位的8开头,

**Comment by any86** [comment]
试试这个行不行
```
/^(\+?62|0)8(1[123456789]|2[1238]|3[1238]|5[12356789]|7[78]|9[56789]|8[123456789])([\s?|\d]{5,11})$/
```

**Comment by any86** [comment]
我百度的是62开头
https://www.chahaoba.com/%E5%8D%B0%E5%BA%A6%E5%B0%BC%E8%A5%BF%E4%BA%9A

**Comment by zdd-jgt** [comment]
好的，谢谢
