### ISSUE TITLE
为什么主页打不开了，有人遇到过么？

### ISSUE THREAD

**Issue by wuxiaobin1995** [any86/any-rule#120]
![image](https://user-images.githubusercontent.com/36044379/89249596-2fb99380-d645-11ea-8841-e2903154e243.png)

**Comment by any86** [comment]
可以啊, 没打错网址吧?
https://any86.github.io/any-rule/

**Comment by gaoqiang19514** [comment]
> 可以啊, 没打错网址吧?
> https://any86.github.io/any-rule/

现在打不开了

**Comment by any86** [comment]
不会啊, 我让别人试了能打开

**Comment by any86** [comment]
> > 可以啊, 没打错网址吧?
> > https://any86.github.io/any-rule/
> 
> 现在打不开了

报什么错?

**Comment by gaoqiang19514** [comment]
> > > 可以啊, 没打错网址吧?
> > > https://any86.github.io/any-rule/
> > 
> > 
> > 现在打不开了
> 
> 报什么错?

![image](https://user-images.githubusercontent.com/13738577/89401481-ed2caf80-d747-11ea-99d0-aef494f087b5.png)

**Comment by any86** [comment]
找了几个人帮试过了, 都可以啊

**Comment by gaoqiang19514** [comment]
> 找了几个人帮试过了, 都可以啊
难道是我公司网络的原因？思考

**Comment by any86** [comment]
@gaoqiang19514  有可能, 我朋友在深圳的最近几天打不开github

**Comment by wuxiaobin1995** [comment]
我估计是域名污染了，部分地区上不了.io，我直接修改host就可以打开！
