### ISSUE TITLE
18位卡号的校验不了

### ISSUE THREAD

**Issue by nayunfeng** [any86/any-rule#123]
像杭州银行

**Comment by any86** [comment]
能提供一个具体的号码吗

**Comment by nayunfeng** [comment]
> 能提供一个具体的号码吗

603367100133087342
我尝试修改了下原有的正则表达式,目前校验通过了.这是我改之后的:^(?:[1-9]{1})(?:\d{15}|\d{17}|\d{18})$

**Comment by any86** [comment]
好的感谢反馈, 我仔细研究下发版

**Comment by nayunfeng** [comment]
> 好的感谢反馈, 我仔细研究下发版

谢谢,么么大

**Comment by any86** [comment]
我才发现, 我的银行卡正则可以过你提供的那条啊? 你看到的正则是什么?
是```/^[1-9]\d{9,29}$/```吗?

**Comment by nayunfeng** [comment]
> 我才发现, 我的银行卡正则可以过你提供的那条啊? 你看到的正则是什么?
> 是`/^[1-9]\d{9,29}$/`吗?

对的哈,你的仓库是这个,我看到的是/^(?:[1-9]{1})(?:\d{15}|\d{18})$/,来自于https://tools.miku.ac/any_rule/这个网站

**Comment by any86** [comment]
哈哈, 那个正则是很久以前的啦, 很早就有人提了issue已经改喽

**Comment by any86** [comment]
现在的正则是参考微信支付官方文档部分列出的银行卡号进行的整理, 很稳

**Comment by nayunfeng** [comment]
> 现在的正则是参考微信支付官方文档部分列出的银行卡号进行的整理, 很稳

嗯嗯,目前没啥问题了
