### ISSUE TITLE
公交站点名称

### ISSUE THREAD

**Issue by zhangchenglin** [any86/any-rule#124]
数字+汉字+中文圆括号+少量字母符号

他们的关系是可以共存，但不一定共存，最后是总长度控制。

个人感觉组成结构会是这些，望有识之士补充或推翻。
望采纳。

**Comment by any86** [comment]
这个还真的是比较少见的需求, 我明天白天观察下路边的车站牌

**Comment by zhangchenglin** [comment]
> 这个还真的是比较少见的需求, 我明天白天观察下路边的车站牌

现在可以网上查公交呢，不一定非得去站台看去，要查航班号规律的话，也不是非得去机场啊。
😋😋😋😋😋

**Comment by any86** [comment]
其实公交站我们这边都是纯汉字为必填, 也没有什么其他约束, 所以这个估计只能靠数据库去约束, 正则约束不了啊
