### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by loo41** [any86/any-rule#13]
库是挺好的，但是这样每次复制粘贴用起来不方便。
- 发布成 npm 包是否更好了，使用方便。
- 发布一个 vscode 正则常用自动补全插件。

**Comment by any86** [comment]
发布vscode确实是个好点子, 我想下交互然后做, 真是个好点子, 感谢! 👍 

发布npm暂时不想做了, 因为和我的初衷定位不一样了, 我是觉得很多人应该就是想用的时候才查百度, 才做的这个,  为了他们更放方便也更准确.
让他们按上包, 他们用的时候还是要看文档, 因为一旦做成api就要用英文, 正则很多人都并不是常用的, 所以应该不会记住api, 都要查的. 而且英文api对中国开发者可能并不方便了. 我再想想有啥办法解决这个再做api

**Comment by any86** [comment]
vscode插件第一版上线了, 感谢你给我的建议, 欢迎测试

https://marketplace.visualstudio.com/items?itemName=russell.any-rule
