### ISSUE TITLE
正则修改

### ISSUE THREAD

**Issue by mingze6576** [any86/any-rule#130]
现在是可输入 数字 + 字母  或者   数字   + 特殊符号
改成 可输入 数字  +   字母  + 特殊符号
/^(?=.*[0-9])((?=.*[a-z])[0-9a-z]+|(?=.*[!@#$%^&*])[0-9!@#$%^&*]+)(){6,12}$/

**Comment by any86** [comment]
```javascript
/^(?=.*[a-zA-Z])(?=.*\d)(?=.*[!@#$%^&*? ]).+$/
```
3者必须共存, 是这个意思吗?

**Comment by any86** [comment]
![Uploading image.png…]()
