### ISSUE TITLE
我有更好的正则: email地址

### ISSUE THREAD

**Issue by 1097171985** [any86/any-rule#14]
这个正则 为啥  放在oc上面不能使用呢？

**Comment by any86** [comment]
抱歉oc我也不懂哦(⊙_⊙)? oc正则应该是js有些不一样吧.

**Comment by 1097171985** [comment]
哦哦，应该是跟转义符这样的问题！你这个好用，我分享给我的伙伴了

**Comment by loveuqian** [comment]
> 哦哦，应该是跟转义符这样的问题！你这个好用，我分享给我的伙伴了

能把你这个 email 正则的 oc 代码发一下吗？
