### ISSUE TITLE
新能源车牌号校验有问题呀，京AA

### ISSUE THREAD

**Issue by ChinaNumber-One** [any86/any-rule#148]

**Comment by any86** [comment]
请提供一下完整的车牌

**Comment by dyb881** [comment]
/^[京津沪渝冀豫云辽黑湘皖鲁新苏浙赣鄂桂甘晋蒙陕吉闽贵粤青藏川宁琼使领]{1}[A-HJ-NP-Z]{1}(?:(([0-9]{5}[A-HJK])|([A-HJK][A-HJ-NP-Z0-9][0-9]{4}))|[A-HJ-NP-Z0-9]{4}[A-HJ-NP-Z0-9挂学警港澳]{1})$/ 试试这个？还没测

**Comment by any86** [comment]
感谢已修复
