### ISSUE TITLE
新能源车牌的规则更改

### ISSUE THREAD

**Issue by dyb881** [any86/any-rule#149]
测试车牌：粤BAA1234

 新能源车牌的规则如下，你看看车牌号的较验规则有没有适配以下规则：

说明：绿牌车，车牌位数是7位，新能源汽车号牌为渐变绿色，大型新能源汽车号牌为黄绿双拼色
--新能源车牌号组成包含字母D（纯电）或者F（混电），字母在前为新能源小车，在后为新能源大车
小型车，那车牌号的长度是8位，且第3位字母为“(D\A\B\C\E)纯电动汽车、(F\G\H\J\K)非纯电动汽车"，
大型车，第8位字母为“(D\A\B\C\E)纯电动汽车、(F\G\H\J\K)非纯电动汽车"。

**Comment by dyb881** [comment]
/^[京津沪渝冀豫云辽黑湘皖鲁新苏浙赣鄂桂甘晋蒙陕吉闽贵粤青藏川宁琼使领]{1}[A-HJ-NP-Z]{1}(?:(([0-9]{5}[A-HJK])|([A-HJK][A-HJ-NP-Z0-9][0-9]{4}))|[A-HJ-NP-Z0-9]{4}[A-HJ-NP-Z0-9挂学警港澳]{1})$/ 试试这个？还没测

**Comment by any86** [comment]
感谢已修复

**Comment by any86** [comment]
感谢已修复
