### ISSUE TITLE
博主您好

### ISSUE THREAD

**Issue by Hey-Bin** [any86/any-rule#15]
我是在掘金上看到您的文章，您写的真好。是这样的，我这边在做一个车辆VIN的校验,您能帮我写一下吗，谢谢您了

**Comment by any86** [comment]
可以, 但是我不第一次听说vin这个恭喜, 你简答说下格式要求, 我也百度下格式

**Comment by any86** [comment]
车架号啊, 是要匹配国际, 还是只要中国即可?

**Comment by Hey-Bin** [comment]
应该是国际标准，公司有一些进口车
示例 : 1G1BL52P7TR115520
信息为：1996年、GM(或Suzuki)、产地：美国。
tonylei
May 17 2006, 12:18 PM

**Comment by any86** [comment]
好的, 我写下, 等会 :whale:

**Comment by Hey-Bin** [comment]
好的，谢谢您了

**Comment by any86** [comment]
https://jingyan.baidu.com/album/5bbb5a1b1dad7413eaa1796e.html?picindex=2

https://baike.baidu.com/item/%E8%BD%A6%E8%BE%86%E8%AF%86%E5%88%AB%E5%8F%B7%E7%A0%81/4338309?fr=aladdin

这个规则有没有精准的说明, 看了几个感觉都不一样呢, 不知道那个对, 而且感觉好像都不对, 我先教你几个关键的知识点, 如果你对他的规则很了解你先自己试试,下面的知识点应该就够了, 我也在仔细看下他的规则:
```
/^[1-6,9,w,t]$/ // 匹配1到6和9和w和t

/[0-9,A-Z]/ // 匹配数字和大写字母

/^[^1]$/ // 不包含数字1

```

**Comment by Hey-Bin** [comment]
嗯，好的，谢谢您了

**Comment by any86** [comment]
https://blog.csdn.net/shenhonglei1234/article/details/53103161
https://blog.csdn.net/ajianchina/article/details/70227234
这规则我是真没看明白, 我现在给你一个校验了**位数/第一位国家编码**的正则, 看看够不够你们用:

``` javascript
/^[1-6,9,J,K,L,R,S,T,V,W,Y,Z][0-9,A-Z,a-z]{16}$/.test('1G1BL52P7TR115520') // true
```

**Comment by any86** [comment]
我想起了手机号的正则, 之前做过调查, 很多人因为怕录入不进去都只是匹配11为数字即当做手机号, 至于手机号是否合法都交给了后端在数据库中验证 ,你这个是不是也一样呢?

**Comment by Hey-Bin** [comment]
前后端都要校验，这个vin我也不太懂，应该够用了，真是麻烦您了，谢谢您

**Comment by any86** [comment]
客气客气, 我本来想给你写全面点的, 但是真实没读懂vin的规则.. 🐳 whale

**Comment by Hey-Bin** [comment]
我昨天看了一天，它这个有不同的说法，没有准确的信息，做起来有难度

**Comment by any86** [comment]
我看好像有个校验位还要做"余数"计算, 那个正则恐怕做不了.
既然后端也验证, 为了保险起见, 我建议用这条:
```javascript
/^[0-9,A-Z,a-z]{17}$/.test('1G1BL52P7TR115520') // true
```

**Comment by Hey-Bin** [comment]
好的，麻烦您了，谢谢

**Comment by any86** [comment]
客气 🐳
