### ISSUE TITLE
正则语法需要改进

### ISSUE THREAD

**Issue by scscms** [any86/any-rule#150]
很多一些可以改进的写法：
[京津沪...]{1}    说明：直接删除多余的{1}   正则里就不应该出现{1}
[1|5|7]     说明：直接写[157]     类似的还有[1|8|9]括号内本身就表示其中之一，与|或的用法重复。
[a-zA-Z0-9_]*    说明：直接写\w*
[-_a-zA-Z0-9]   说明：同上改成 [\w-]
/^$/   说明：需要转译 /^<\!--[\s\S]*?-->$/   本身没错，可能会影响编辑器

**Comment by any86** [comment]
感谢已修复, 另外请问这句什么意思?

> /^$/ 说明：需要转译 /^$/ 本身没错，可能会影响编辑器

**Comment by scscms** [comment]
意思是是html注释标签，某些编辑器可能会显示异常。也可能会被误(nodejs正则之类的)。如果转译一下更好 <\!--  -->

**Comment by any86** [comment]
好的, 3q
