### ISSUE TITLE
没找到 README 中提到的 develop 分支

### ISSUE THREAD

**Issue by richex-cn** [any86/any-rule#155]
README 中提到说 PR 提交到 develop 分支（<https://github.com/any86/any-rule/blob/8e32df889ed2e4b5576febe1751c9aa9606717d4/README.md#fire%E5%85%B3%E4%BA%8Epr>），但是已有分支好像没看到这个分支。

![image](https://user-images.githubusercontent.com/25103518/110233078-8cbf5400-7f5c-11eb-9693-a164ed1e5636.png)

**Comment by any86** [comment]
忘记了合并的事, 我当时觉得没啥用就把分支删了, 我一会恢复
