### ISSUE TITLE
我有更好的正则: 校验yyyyMMddHHmmss

### ISSUE THREAD

**Issue by z589533** [any86/any-rule#165]
时间格式：yyyyMMddHHmmss.例如：20161213232255

^((([0-9]{3}[1-9]|[0-9]{2}[1-9][0-9]{1}|[0-9]{1}[1-9][0-9]{2}|[1-9][0-9]{3})(((0[13578]|1[02])(0[1-9]|[12][0-9]|3[01]))|((0[469]|11)(0[1-9]|[12][0-9]|30))|(02(0[1-9]|[1][0-9]|2[0-8]))))|((([0-9]{2})(0[48]|[2468][048]|[13579][26])|((0[48]|[2468][048]|[3579][26])00))0229))([0-1]?[0-9]|2[0-3])([0-5][0-9])([0-5][0-9])$

**Comment by kiccer** [comment]
感觉没什么地方用得上呢。。

**Comment by any86** [comment]
感谢
