### ISSUE TITLE
校验yyyyMMdd 精确到日

### ISSUE THREAD

**Issue by z589533** [any86/any-rule#166]
即年月日，格式：yyyyMMdd，例如：20161213

^((([0-9]{3}[1-9]|[0-9]{2}[1-9][0-9]{1}|[0-9]{1}[1-9][0-9]{2}|[1-9][0-9]{3})(((0[13578]|1[02])(0[1-9]|[12][0-9]|3[01]))|((0[469]|11)(0[1-9]|[12][0-9]|30))|(02(0[1-9]|[1][0-9]|2[0-8]))))|((([0-9]{2})(0[48]|[2468][048]|[13579][26])|((0[48]|[2468][048]|[3579][26])00))0229))$

**Comment by any86** [comment]
感谢, 稍后我校验一下合并到代码里

**Comment by any86** [comment]
感谢, 已追加类似: https://github.com/any86/any-rule#%E5%8F%AF%E4%BB%A5%E8%A2%ABmoment%E8%BD%AC%E5%8C%96%E6%88%90%E5%8A%9F%E7%9A%84%E6%97%B6%E9%97%B4-yyyymmdd-hhmmss
