### ISSUE TITLE
网址的正则需要改进

### ISSUE THREAD

**Issue by hellohejinyu** [any86/any-rule#175]
`/^(((ht|f)tps?):\/\/)?[\w-]+(\.[\w-]+)+([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?$/` 这个正则有问题，可以匹配成功 `may.31`，`p38.39` 等字符串。我们用户提了线上 bug 了😆
![image](https://user-images.githubusercontent.com/8766034/120272906-5cc7e880-c2e0-11eb-90af-a762ebcadfc5.png)

网上搜了一圈，关于网址的正则有太多选择了，我也不知道哪个会比较好。就不给建议了😊

**Comment by any86** [comment]
数字结尾没有吗? 我也是参考了很多网上的综合改的,  这个暂时我先不改了, 因为我也不确定数字结尾这种是不是错误的, 等懂的人来指点下吧

**Comment by any86** [comment]
https://baike.baidu.com/item/%E9%A1%B6%E7%BA%A7%E5%9F%9F%E5%90%8D#7

好像允许出现数字, 只是暂时没见过有数字的

**Comment by hellohejinyu** [comment]
> https://baike.baidu.com/item/%E9%A1%B6%E7%BA%A7%E5%9F%9F%E5%90%8D#7
> 
> 好像允许出现数字, 只是暂时没见过有数字的

![image](https://user-images.githubusercontent.com/8766034/120274963-3192c880-c2e3-11eb-927c-4a795b753a79.png)
![image](https://user-images.githubusercontent.com/8766034/120275068-571fd200-c2e3-11eb-99e8-c5d509026572.png)

Chrome 目前对于数字结尾的都是不当做域名处理的，但是从你上面发的规范上来看是允许数字的，有点乱🤪

**Comment by any86** [comment]
等等看有没有这方面的大神给指点下, 问题暂时先不关

**Comment by zgayjjf** [comment]
顶级域名只能是字母，没有数字（另外有部分IDN域名，例如`.中国`）。
如果要支持纯数字的顶级域，那就没办法区分一个包含三级子域名的域名和 ip，比如 `12.32.33.31` 到底是个域名还是 ip。
所以只要支持纯字母和部分 IDN 域名就好了。

[IANA Root Zone Database](https://www.iana.org/domains/root/db)
[互联网顶级域列表
](https://zh.wikipedia.org/wiki/%E4%BA%92%E8%81%94%E7%BD%91%E9%A1%B6%E7%BA%A7%E5%9F%9F%E5%88%97%E8%A1%A8)

**Comment by any86** [comment]
@zgayjjf 感谢, 就需要一个大牛帮忙确认, 3q, 稍后发版

**Comment by zgayjjf** [comment]
> @zgayjjf 感谢, 就需要一个大牛帮忙确认, 3q, 稍后发版

响应太迅速了

**Comment by any86** [comment]
@zgayjjf 正好看到邮件,^_^

**Comment by zurmokeeper** [comment]
> @zgayjjf 正好看到邮件,^_^

大佬，这个url的范围实在是太广了，建议参考下joi  string.url() 方法的实现，（或者引用其他模块）（源码）https://github.com/sideway/address/blob/master/lib/uri.js，
也可以看下 https://github.com/sideway/address/blob/master/test/uri.js   这个模块的测试用例。

**Comment by any86** [comment]
@zurmokeeper  好的, 十分感谢, 稍后修正

**Comment by any86** [comment]
根据大家的反馈, 修改了URL正则, 源码已修改, 暂时先不发版, 请大家试试是否满足各自的需求
```javascript
/^(((ht|f)tps?):\/\/)?([^!@#$%^&*?.\s-]([^!@#$%^&*?.\s]{0,63}[^!@#$%^&*?.\s])?\.)+[a-z]{2,6}\/?/
```
