### ISSUE TITLE
台胞证号码、港澳通行证号码

### ISSUE THREAD

**Issue by GuiYangGan** [any86/any-rule#180]
台胞证：`/^(?:(830000(?:19|20)\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\d|3[01])\d{3}[\dX])|\d{10}[(][DAB][)])$/`
港澳通行证：`/^[CW]([a-z]|[A-Z]|[0-9])\d{7}$/`
这两个是我在这个网站上看到的[http://www.qilin668.com/](http://www.qilin668.com/)，不知是否可以录入进去

**Comment by any86** [comment]
感谢下一个版本增加

**Comment by any86** [comment]
台胞证不对, 是8-10位, 港澳有说9位的, 但是好像还有不同版本, 所以暂时不更新这2个了, 等有人确切的知道规则我再补上, 依然感谢你的提交
