### ISSUE TITLE
我有更好的正则: 中文姓名

### ISSUE THREAD

**Issue by Tomorrowxxy** [any86/any-rule#183]
/^[\p{Han}·]{3,6}+$/u

**Comment by any86** [comment]
感谢, 是个好思路, 这样也许就能做其他东亚语言的正则了, 让我稍微研究下一起更新

**Comment by Tomorrowxxy** [comment]
当前 `/^(?:[\u4e00-\u9fa5·]{2,16})$/` 正则PHP环境下有些问题，并没有得到想要的结果

**Comment by any86** [comment]
没测过php哦, 这个是js的正则, 可能是2个语言正则有差异吧

**Comment by Tomorrowxxy** [comment]
当前列表大部分通用，可以的话建议标记区分语言

**Comment by any86** [comment]
好的, 主要我也不知道哪些通用不通啊😂, 这个设计之初就是给前端用的, 没想到其他语言开发者也会用. 之前还有个人要oc版本, 我也不会啊, 哈哈

**Comment by Tomorrowxxy** [comment]
哈哈哈 毕竟这么多star

**Comment by any86** [comment]
我尽量保证"雨露均沾"🤩

**Comment by ZhangChengLin** [comment]
> 我尽量保证"雨露均沾"🤩

现在这么多的星星了，看看能不能让更多人能受益。
既然前端可以进行测试，按说后端也能测试，不同语言的正则应该会收货更多闪闪的红星呢。
