### ISSUE TITLE
我有更好的正则: 身份证号, 支持1/2代(15位/18位数字)

### ISSUE THREAD

**Issue by jh0904** [any86/any-rule#190]
身份证严格校验，包含年份、月份的校验，支持15，18位身份证
^\d{6}((((((19|20)\d{2})(0[13-9]|1[012])(0[1-9]|[12]\d|30))|(((19|20)\d{2})(0[13578]|1[02])31)|((19|20)\d{2})02(0[1-9]|1\d|2[0-8])|((((19|20)([13579][26]|[2468][048]|0[48]))|(2000))0229))\d{3})|((((\d{2})(0[13-9]|1[012])(0[1-9]|[12]\d|30))|((\d{2})(0[13578]|1[02])31)|((\d{2})02(0[1-9]|1\d|2[0-8]))|(([13579][26]|[2468][048]|0[048])0229))\d{2}))(\d|X|x)$

**Comment by any86** [comment]
感谢,稍后合并
