### ISSUE TITLE
你好，请问是否有最新的正则数据获取接口呢?

### ISSUE THREAD

**Issue by Linindoo** [any86/any-rule#194]
我目前是使用的这个地址来获取你们的正则数据[https://raw.githubusercontent.com/any86/any-rule/v0.3.7/packages/www/src/RULES.js](url)，但是因为github在国内不稳定，经常会失效，不知道你们有什么解决方案，是否有cdn？

**Comment by any86** [comment]
暂时没有, 因为vscode中有些限制造成正则一定要编译到程序中, 稍后我研究出一个cdn连接,感谢反馈
