### ISSUE TITLE
快捷方式3无法唤起插件功能

### ISSUE THREAD

**Issue by estoi** [any86/any-rule#195]
方式3:在代码任意位置输入"@zz".

vscode在代码中键入@zz无法唤起插件功能

vscode版本：1.60.1

**Comment by any86** [comment]
感谢反馈, 我估摸是新版vscode改什么api了, 待我研究下

**Comment by any86** [comment]
已解决, 稍后发版本

**Comment by estoi** [comment]
> 已解决, 稍后发版本

新版本没有在插件市场发布吗

**Comment by any86** [comment]
发不上去不知道为啥, 昨天和今天早上都试了不行, 一会下午再试试
