### ISSUE TITLE
护照（包含香港、澳门）是否缺少EHxxxx的匹配

### ISSUE THREAD

**Issue by YuanjianZhang** [any86/any-rule#199]
根据[出入境手册](https://www.nia.gov.cn/n741440/n741547/c1197066/content.html)上描述：
> 2017年4月5日起新的电子普通护照号码生成规则变为：第一位仍是前缀字母“E”，第二位改为顺序使用英文字母（“I”、“O”除外），第三位起7位阿拉伯数字，护照号码总位数仍为9位。  

护照匹配可能缺少了EH这种情况的匹配？ 因为网络上找不到什么资料，也不是很确定。

**Comment by any86** [comment]
感谢, 按照规则修改了下, 稍后我再好好确定下更新到新版:
 /(^[EeKkGgDdSsPpHh]\d{8}$)|(^(([Ee][a-fA-Fj-nJ-Np-zP-Z])|([DdSsPp][Ee])|([Kk][Jj])|([Mm][Aa])|(1[45]))\d{7}$)/
