### ISSUE TITLE
网址正则验证不通过

### ISSUE THREAD

**Issue by slowingbring** [any86/any-rule#202]
https://www.amap.com/search?id=BV10060895&city=420111&geoobj=113.207951%7C29.992557%7C115.785782%7C31.204369&query_type=IDQ&query=%E5%85%89%E8%B0%B7%E5%B9%BF%E5%9C%BA(%E5%9C%B0%E9%93%81%E7%AB%99)&zoom=10.15

**Comment by any86** [comment]
马上新版发布
