### ISSUE TITLE
我有更好的正则: 网址正则需修改

### ISSUE THREAD

**Issue by Tadini** [any86/any-rule#207]
/^(((ht|f)tps?):\/\/)?[\w-]+(\.[\w-]+)+([\w.,@?^=%&:/~+#-\(\)]*[\w@?^=%&/~+#-\(\)])?$/
校验网址  
https://vuejs.org/v2/api/#v-model
【表现】不通过
稍作修改后校验网址 （此网址不存在只做校验用）
https://vuejs.org/v-2/api/#v-model
【表现】不通过

建议修改：/^(((ht|f)tps?):\/\/)?[\w-]+(\.[\w-]+)+([\w.,@?^=%&:/~+#\-\(\)]*[\w@?^=%&/~+#\-\(\)])?$/

**Comment by any86** [comment]
感谢, 稍后做修正
