### ISSUE TITLE
子网掩码的正则问题

### ISSUE THREAD

**Issue by 2462870727** [any86/any-rule#208]
子网掩码正则应该是错误，

192.168.0.1 会通过正则匹配，实际上这并不是 子网掩码。
关于子网掩码的 讲解 这篇[文章](https://blog.csdn.net/weixin_39291021/article/details/105218513) ，应该说的是正确的

**Comment by any86** [comment]
感谢, 稍后修正

**Comment by 2462870727** [comment]
你好 我这边晚点会提交一个pr

**Comment by any86** [comment]
太好了, 正好我也什么头绪,感谢

**Comment by 2462870727** [comment]
不谢 生态应该共同维护

**Comment by 2462870727** [comment]
#209

**Comment by any86** [comment]
已合并, 感谢
