### ISSUE TITLE
“linux文件夹路径”和“linux文件路径”问题

### ISSUE THREAD

**Issue by Lce-Lemon** [any86/any-rule#214]
/ a a / a / a    a     /
斜杠前后不应该有空格的吧

**Comment by any86** [comment]
我试了下, 可以建立带空格的文件夹

**Comment by Lce-Lemon** [comment]
可以创建前后有空格的文件夹？
文件夹中间是可以带空格的，但是前后是不能带空格的

**Comment by any86** [comment]
可以啊, 我在部位建立了一个, 我现在没有linux环境, 我有linux下的ftp, 我就通过FileZilla简历一个"asd "的文件夹
![image](https://user-images.githubusercontent.com/8264787/146724375-59371c76-5825-4164-a21d-951a08924a25.png)

**Comment by Lce-Lemon** [comment]
我去，前面呢，前面可以有空格吗，学到了

**Comment by any86** [comment]
也可以了😂

**Comment by Lce-Lemon** [comment]
学到了，我艹
