### ISSUE TITLE
我有更好的正则: 网址(url,支持端口和"? 参数"和"

### ISSUE THREAD

**Issue by Wang-Yang** [any86/any-rule#215]
原正则不能匹配这样的网址：https://lanhuapp.com/web/#/item/project/detailDetach?pid=52f0b5d0-df36-49ce-8335-0d07ebd5b988&project_id=52f0b5d0-df36-49ce-8335-0d07ebd5b988&image_id=dd506ebd-ffaf-4569-9e19-65060ae37c35&fromEditor=true

这个可以匹配网址，带端口, #, ip:  /^(https?:\/\/(([a-zA-Z0-9]+-?)+[a-zA-Z0-9]+\.)+[a-zA-Z0-9]+)(:\d+)?(\/.*)?(\?.*)?(#.*)?$/

**Comment by any86** [comment]
感谢, 这条之前已经改了, 但是没有发版, 新版的是这个:
```javascript
/^(((ht|f)tps?):\/\/)?([^!@#$%^&*?.\s-]([^!@#$%^&*?.\s]{0,63}[^!@#$%^&*?.\s])?\.)+[a-z]{2,6}\/?/
```
我试了你提供的网址可以通过, 如果你对这条正则不无异议, 我一会下午发个版本
