### ISSUE TITLE
匹配日期的正则（能够匹配闰年日期）

### ISSUE THREAD

**Issue by chitongyu** [any86/any-rule#226]
日期正则：/^\d{1,4}(-)(1[0-2]|0?[1-9])\1(0?[1-9]|[1-2]\d|30|31)$/
问题：无法匹配到闰年的日期
改进正则：/^(([0-9]{3}[1-9]|[0-9]{2}[1-9][0-9]{1}|[0-9]{1}[1-9][0-9]{2}|[1-9][0-9]{3})-(((0[13578]|1[02])-(0[1-9]|[12][0-9]|3[01]))|((0[469]|11)-(0[1-9]|[12][0-9]|30))|(02-(0[1-9]|[1][0-9]|2[0-8]))))|((([0-9]{2})(0[48]|[2468][048]|[13579][26])|((0[48]|[2468][048]|[3579][26])00))-02-29)$/
匹配结果：
![image](https://user-images.githubusercontent.com/23652139/160753732-aede094f-e4bd-45ae-8d83-4a1a7104850e.png)
（ps：非本人所写，只是觉得写的更好）

**Comment by any86** [comment]
感谢, 稍后合并.
