### ISSUE TITLE
省份的正则，可以完善下

### ISSUE THREAD

**Issue by hyaray** [any86/any-rule#227]
浙江|上海|北京|天津|重庆|黑龙江|吉林|辽宁|内蒙古|河北|新疆|甘肃|青海|陕西|宁夏|河南|山东|山西|安徽|湖北|湖南|江苏|四川|贵州|云南|广西|西藏|江西|广东|福建|台湾|海南|香港|澳门

**Comment by any86** [comment]
好的感谢
