### ISSUE TITLE
我有更好的正则: 小数

### ISSUE THREAD

**Issue by ld269440877** [any86/any-rule#234]
[+-]?(\d+([.]\d*)?([eE][+-]?\d+)?|[.]\d+([eE][+-]?\d+)?)

123
123.
123.24
.24
2e-2 = 2 * 10 pow -2 = 2 * 0.1
4E+4 = 4 * 10 pow 4 = 4 * 10 000

**Comment by any86** [comment]
感谢反馈, 稍后同步
