### ISSUE TITLE
正整数

### ISSUE THREAD

**Issue by oneday219** [any86/any-rule#24]

**Comment by any86** [comment]
什么问题?

**Comment by oneday219** [comment]
非常感谢您的回复，我有些疑问就是说，前端的基本情况都可以满足，就是代码的阅读上，编写习惯上不是很好，模棱两可，刚换了一家规模比较大的，代码规范不是很好，比如说vue中对axios和async的接口请求得封装，感觉就是乱糟糟的，想请问你这种情况改怎么处理，或者您这边有什么好的demo或者建议



------------------ 原始邮件 ------------------
发件人: "any86"<notifications@github.com>; 
发送时间: 2019年8月13日(星期二) 下午2:59
收件人: "any86/any-rule"<any-rule@noreply.github.com>; 
抄送: "无罪的罪人"<706652805@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [any86/any-rule] 正整数 (#24)




什么问题?

**Comment by any86** [comment]
这个超出我这个插件解决的问题的范围了哦,  所以我就说下我这边解决方式, 但是不是最好的, 只是我自己的:
1. 接口链接自己要有一个文件(夹)管理.
2. 用axios自己对不同要求的接口分别实例化, 一般不同域名下的接口可能拦截器/头信息/异常处理等都是不一样的
3. 如果你用的是vue可以把提示类组件用函数包裹下, 直接放在异常处理的回调中. 包裹函数我封装过, 你可以试下这个: https://github.com/any86/vue-create-root

暂时就想起这么多.

**Comment by oneday219** [comment]
好的，明白了,多谢指教



------------------ 原始邮件 ------------------
发件人: "any86"<notifications@github.com>; 
发送时间: 2019年8月14日(星期三) 上午9:04
收件人: "any86/any-rule"<any-rule@noreply.github.com>; 
抄送: "无罪的罪人"<706652805@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [any86/any-rule] 正整数 (#24)




这个超出我这个插件解决的问题的范围了哦,  所以我就说下我这边解决方式, 但是不是最好的, 只是我自己的:
  
接口链接自己要有一个文件(夹)管理.
 
用axios自己对不同要求的接口分别实例化, 一般不同域名下的接口可能拦截器/头信息/异常处理等都是不一样的
 
如果你用的是vue可以把提示类组件用函数包裹下, 直接放在异常处理的回调中. 包裹函数我封装过, 你可以试下这个: https://github.com/any86/vue-create-root
  
暂时就想起这么多.

**Comment by any86** [comment]
@oneday219 客气

**Comment by oneday219** [comment]
方便的话，您能给一个比较完整的项目吗，没别的意思，就是学习学习



------------------ 原始邮件 ------------------
发件人: "any86"<notifications@github.com>; 
发送时间: 2019年8月16日(星期五) 上午9:37
收件人: "any86/any-rule"<any-rule@noreply.github.com>; 
抄送: "无罪的罪人"<706652805@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [any86/any-rule] 正整数 (#24)




@oneday219 客气

**Comment by any86** [comment]
@oneday219 这个不行啊, 单位的项目, 这有开源的项目你可以参考: https://github.com/PanJiaChen/vue-element-admin

**Comment by oneday219** [comment]
好嘞，加您QQ方便吗，以后好想您请教



------------------ 原始邮件 ------------------
发件人: "any86"<notifications@github.com>; 
发送时间: 2019年8月16日(星期五) 上午9:44
收件人: "any86/any-rule"<any-rule@noreply.github.com>; 
抄送: "无罪的罪人"<706652805@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [any86/any-rule] 正整数 (#24)




@oneday219 这个不行啊, 单位的项目, 这有开源的项目你可以参考: https://github.com/PanJiaChen/vue-element-admin

**Comment by any86** [comment]
@oneday219 我很少看qq的 都是上班族 qq聊和公司无关的的不好交代啊... 还是github吧 , 领导不在的时候我就给你回复, 比较方便

**Comment by oneday219** [comment]
好的好的



------------------ 原始邮件 ------------------
发件人: "any86"<notifications@github.com>; 
发送时间: 2019年8月16日(星期五) 上午9:48
收件人: "any86/any-rule"<any-rule@noreply.github.com>; 
抄送: "无罪的罪人"<706652805@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [any86/any-rule] 正整数 (#24)




@oneday219 我很少看qq的 都是上班族 qq聊和公司无关的的不好交代啊... 还是github吧 , 领导不在的时候我就给你回复, 比较方便
