### ISSUE TITLE
同时使用 Yarn 和 NPM 容易产生混淆

### ISSUE THREAD

**Issue by richex-cn** [any86/any-rule#244]
有一个疑问，Yarn 和 NPM 两者同为包管理工具，同时存在一个项目中，很难分清楚项目现在使用的是哪一个，并且两个 lockfile 在不同的开发者之间也很容易出现版本不一致的情况，存在一些隐患。所以是否是有特殊需求需要两个 Package Manager，如果没有的话，建议保留一个就可以了。

**Comment by any86** [comment]
感谢提醒, 一直是我自己开发, 所以我也没太留意这个,  这2个都不要了, 稍后我换成pnpm, 我别的项目都开始用pnpm了, 他也有自己的lock

**Comment by richex-cn** [comment]
@any86 那关闭这个 issue 就交给你在 commit 中处理了哈~

**Comment by any86** [comment]
时间关系, 暂时只用yarn
