### ISSUE TITLE
写了一个命令行版本, 且支持命令行正则测试功能. 申请推荐.

### ISSUE THREAD

**Issue by shenguanjiejie** [any86/any-rule#254]
[https://github.com/shenguanjiejie/workwork](https://github.com/shenguanjiejie/workwork)
效果如下(顺便还支持了正则命令行测试功能):
![regex](https://github.com/shenguanjiejie/workwork/blob/main/resources/regex.png?raw=true)

**Comment by any86** [comment]
首页已更新
