### ISSUE TITLE
[vscode feedback] 统一社会信用代码(宽松匹配)(15位/18位/20位数字/字母)

### ISSUE THREAD

**Issue by you-hengh** [any86/any-rule#257]
身份证号码怎么有 20 位呢?  这是插件提供的正则
> /^(([0-9A-Za-z]{15})|([0-9A-Za-z]{18})|([0-9A-Za-z]{20}))$/

**Comment by any86** [comment]
这不是身份证, 是"统一社会信用代码"

**Comment by you-hengh** [comment]
不好意思
