### ISSUE TITLE
邮箱验证问题

### ISSUE THREAD

**Issue by fariellany** [any86/any-rule#26]
333@qq.c33311111111  为什么这种邮箱都能通过验证？？？

**Comment by any86** [comment]
![image](https://user-images.githubusercontent.com/8264787/63577937-09305300-c5c2-11e9-8e7c-8b0c565757a8.png)
https://zhidao.baidu.com/question/623707888846259844.html
所以这个没错哦, 只是不常见

**Comment by any86** [comment]
```javascript
/^(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/
```
完全符合63个字符, 开头结尾不能是"-"

**Comment by fariellany** [comment]
> ![图片](https://user-images.githubusercontent.com/8264787/63577937-09305300-c5c2-11e9-8e7c-8b0c565757a8.png)
> https://zhidao.baidu.com/question/623707888846259844.html
> 所以这个没错哦，只是不常见

测试跟我说的 说这样的格式也能验证错误  醉了 我该怼他吗   。。。。

**Comment by any86** [comment]
@fariellany 你把连接给他看看呗, 他要是在纠缠你就给他改短点...  不要和测试纠结, 浪费时间.  比如上面的61你可以改短

**Comment by any86** [comment]
改成/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,3}[a-zA-Z0-9])?)*$/

五个长度的域名, 这个他应该满足了吧, 除了问题你再找他说理... 给他个教训...

**Comment by fariellany** [comment]
> 改成/^[a-zA-Z0-9.!#$%&'_+/=?^_`{|}~-]+@a-zA-Z0-9?(?:.a-zA-Z0-9?)_$/
> 
> 五个长度的域名, 这个他应该满足了吧, 除了问题你再找他说理... 给他个教训...

谢谢了

**Comment by any86** [comment]
@fariellany 不客气
