### ISSUE TITLE
web版本中整数正则与readme中的不一致

### ISSUE THREAD

**Issue by nadirvishun** [any86/any-rule#263]
[web版本](https://any86.github.io/any-rule/)中的整数是`/^-?[0-9]\d*$/`，而readme中的是`/^-?[1-9]\d*$/`。

**Comment by any86** [comment]
感谢, readme已修复, vscode稍后发版

**Comment by any86** [comment]
是的, 整数包含0

**Comment by nadirvishun** [comment]
@any86 应该`/^-?[1-9]\d*$/`这个是对的，首位不能是0

**Comment by any86** [comment]
都不对, 又改了, 现在是对的

**Comment by any86** [comment]
这是新的web地址
