### ISSUE TITLE
我有更好的正则: 车牌号(新能源)

### ISSUE THREAD

**Issue by icfy-dmc** [any86/any-rule#281]
目前新能源校验不能满足剔除7位普通燃油车车牌
组成：省份简称（1位汉字）+发牌机关代号（1位字母）+序号（6位）
序号位
小型车：第一位：只能用字母D或字母F，第二位：字母或者数字，后四位：必须使用数字
大型车：前五位：必须使用数字，第六位：只能用字母D或字母F

新：`/^[京津沪渝冀豫云辽黑湘皖鲁新苏浙赣鄂桂甘晋蒙陕吉闽贵粤青藏川宁琼使领][A-HJ-NP-Z](([DF]((?![IO])[a-zA-Z0-9](?![IO]))[0-9]{4})|([0-9]{5}[DF]))$/`

**Comment by any86** [comment]
感谢反馈, 我研究一下
