### ISSUE TITLE
已statr，回车键以及双回车键的正则，求教

### ISSUE THREAD

**Issue by dixiaochang123** [any86/any-rule#32]
遇到一个问题，文本中每个段落有两个回车符（紧挨着），要把回车符转成<br />，但是每次转的时候都是换成两个回车符，求教一下，怎么一次把两个回车符换成一个换行<br />

**Comment by any86** [comment]
是说换成<br>吗?

**Comment by any86** [comment]
```javascript
`1

2`.replace(/\n{2}/, '<br>')
```

**Comment by dixiaochang123** [comment]
> ```js
> ` 1
> 
> 2 `。replace（/ \ n {2} /，' <br> '）// “ 1 <br> 2”
> ```
> 
> 其实我没太明白你的意思，我看你是说回车符，如果上面的不对，就把\ n改成\ r

您好，是这样的，let dataNew=data.replace(/\r/g,"<br>");，我用这个方法将回车符替换为<br />,但是每次有两个回车符↵↵，然后，我又用let dataNew=data.replace(/\r+/g,"<br>");，结果还是一样，一词替换为两个<br />,我是想将↵↵替换为一个<br />;谢谢您的回复

**Comment by any86** [comment]
```javascript
`1

2`.replace(/\n{2}/g, '<br>') // "1<br>2"
```
我不知道怎么构造/r, 我是mac和win可能有点区别, 你把\n改成\r就ok了, 和你之前写的区别就是`{2}`
