### ISSUE TITLE
日期验证不够严谨

### ISSUE THREAD

**Issue by shanjixiaboss** [any86/any-rule#33]
`/^\d{4}(-)(1[0-2]|0?\d)\1([0-2]\d|\d|30|31)$/.test('2019-02-31')`
验证为true

**Comment by any86** [comment]
已修复, 参考: cnblogs.com/mgod/archive/2007/04/26/728628.html

**Comment by shanjixiaboss** [comment]
🤙

**Comment by any86** [comment]
@shanjixiaboss  感谢老铁的反馈, 哈哈
