### ISSUE TITLE
网址正则会匹配到 ....

### ISSUE THREAD

**Issue by klaus01** [any86/any-rule#47]
`/^(?:(?:https?|ftp):\/\/)?(?:[\da-z.-]+)\.(?:[a-z.]{2,6})(?:\/\w\.-]*)*\/?/` 这个正则会匹配到`....`。这是个错误。
<img width="796" alt="屏幕快照 2019-11-20 下午5 53 14" src="https://user-images.githubusercontent.com/338228/69228513-acdbd000-0bbe-11ea-8468-60aadbff7349.png">

**Comment by any86** [comment]
感谢反馈,嘿

**Comment by klaus01** [comment]
还没发布么？
`https://tools.miku.ac/any_rule/`上看到还是老的。

**Comment by any86** [comment]
@klaus01 那个网站不是我的, 我现在给他发个私信, 告诉他我更新了

**Comment by klaus01** [comment]
哦哦，有点尴尬😅
