### ISSUE TITLE
我有更好的正则: 图片链接地址（图片格式可按需增删）

### ISSUE THREAD

**Issue by Niefee** [any86/any-rule#48]
```js
/^https?:\/\/.*?(\.(?:gif|png|jpg|jpeg|webp|svg|psd|bmp|tif))$/i
```
如`https://www.abc.com/logopng`这类URL不应该被判断为图片链接地址，后缀前应该加`.`号。

**Comment by any86** [comment]
好的感谢指正, 我研究下修改

**Comment by any86** [comment]
久等了, 最近单位和家里都比较忙, 刚修改:
```
/^https?:\/\/(.+\/)+.+(\.(gif|png|jpg|jpeg|webp|svg|psd|bmp|tif))$/i.test('https://www.abc.com/logo.png')
```
![image](https://user-images.githubusercontent.com/8264787/70400454-0de02080-1a66-11ea-857f-72188fcfb0e5.png)

帮忙试下是否还有别的用例不能通过, 你上面说的问题已经解决了. 👽
