### ISSUE TITLE
哇，不错，希望不断壮大！

### ISSUE THREAD

**Issue by gaoqiang19514** [any86/any-rule#5]
稳住！

**Comment by gaoqiang19514** [comment]
希望作者加点测试用例

**Comment by any86** [comment]
一定的, 感谢支持, 马上还要加入一个更灵活的功能:whale:

**Comment by any86** [comment]
> 希望作者加点测试用例

测试用例就是你们的需求啊"whale:

**Comment by gaoqiang19514** [comment]
[ok](http://wx4.sinaimg.cn/large/006r3PQBly1fn7z55l1snj30hs0fpjy1.jpg)

**Comment by gaoqiang19514** [comment]
![ok](http://wx4.sinaimg.cn/large/006r3PQBly1fn7z55l1snj30hs0fpjy1.jpg)
