### ISSUE TITLE
业务中需要一个机身码的正则

### ISSUE THREAD

**Issue by zxf4399** [any86/any-rule#51]
thanks

**Comment by zxf4399** [comment]
@any86

**Comment by any86** [comment]
机身码是"手机代码"吗?
https://baike.baidu.com/item/%E6%89%8B%E6%9C%BA%E4%BB%A3%E7%A0%81/19394504?fr=aladdin

**Comment by zxf4399** [comment]
是的，不好意思，昨天没有看到，对不起 @any86

**Comment by any86** [comment]
```
/^\d{14}0$/
```
我参考了百度百科, 我分析是: 15位, 最后一位为0.  第7/8位虽然有备选值 , 但是考虑到日后新增产地/手机厂商等未知因素, 还是决定不进行更细的限制. 

上面是我个人对规律的总结, 仅仅参考了[百度百科](https://baike.baidu.com/item/%E6%89%8B%E6%9C%BA%E4%BB%A3%E7%A0%81/19394504?fr=aladdin), 如果有更详尽的约束要求可以回复我, 我再给你改改.

**Comment by zxf4399** [comment]
我感觉有点问题，因为我拿我的手机号*306#测试了一下，发现我最后一位是8。然后那个百度百科地址不对，应该是这个[百度百科](https://baike.baidu.com/item/IMEI)

**Comment by any86** [comment]
![image](https://user-images.githubusercontent.com/8264787/70504401-ae1a7000-1b60-11ea-96a9-0262251d007e.png)
你的百科里也说最后一位是0, 算了看来只能校验位数了
```javascript
/^\d{15,17}$/
```

**Comment by zxf4399** [comment]
bingo
