### ISSUE TITLE
缺少火车，车次的校验

### ISSUE THREAD

**Issue by zxf4399** [any86/any-rule#52]
@any86

**Comment by any86** [comment]
好的, 感谢反馈, 我研究下规则

**Comment by any86** [comment]
```javascript
^[GCDZTSPKXLY1-9]\d{4}$
```
不知道我总结的规律对不对, 帮试一下.
![image](https://user-images.githubusercontent.com/8264787/71339535-c0e46a00-258e-11ea-986c-fb4f2ede1a8b.png)

[参考百度百科](https://baike.baidu.com/item/%E8%BD%A6%E6%AC%A1/9702329)

**Comment by zxf4399** [comment]
@any86 不好意思，最近忙着年终总结，今天查看了下，发现基本没问题，谢谢。
