### ISSUE TITLE
正则表达式能否支持移动端？？？

### ISSUE THREAD

**Issue by lilovexin** [any86/any-rule#54]

**Comment by any86** [comment]
我看你github, 你说的移动端是指ios/安卓客户端吧?  但是我只会js啊, 如果有其他客户端开发愿意一起做这项目, 我当然那愿意增加支持"客户端"的正则

**Comment by lilovexin** [comment]
就是iOS端或者Android端的正则

**Comment by any86** [comment]
> 就是iOS端或者Android端的正则

我不会客户端的语言啊, 希望有别的语言的开发者可以也做一个"正则大全"吧

**Comment by lilovexin** [comment]
加个好友，我来帮你做下iOS端的正则。QQ：244158713
