### ISSUE TITLE
我有更好的正则: 身份证号, 支持1/2代(15位/18位数字)

### ISSUE THREAD

**Issue by Airkro** [any86/any-rule#55]
```diff
- /(^\d{8}(0\d|10|11|12)([0-2]\d|30|31)\d{3}$)|(^\d{6}(18|19|20)\d{2}(0\d|10|11|12)([0-2]\d|30|31)\d{3}(\d|X|x)$)/
+ /(^\d{8}(0\d|10|11|12)([0-2]\d|30|31)\d{3}$)|(^\d{6}(18|19|20)\d{2}(0\d|10|11|12)([0-2]\d|30|31)\d{3}([\dXx])$)/
```

用字符组代替多选结构，可以提升性能

**Comment by any86** [comment]
好的十分感谢, 稍后修改, 要不要提个pr参与下?

**Comment by Airkro** [comment]
事实上我发现 eslint-plugin-unicorn 可以优化正则，这个issues也来自于此，我在考虑要不要提个统一的PR 将它集成进项目。

https://github.com/sindresorhus/eslint-plugin-unicorn/blob/HEAD/docs/rules/regex-shorthand.md

不过它的优化不是绝对可靠的，需要人工审核

**Comment by any86** [comment]
我有项目里有测试脚本, 可以简答测试一下, 提价后action会执行test
https://github.com/any86/any-rule/blob/master/__test__/rule.js
