### ISSUE TITLE
我有更好的正则: 密码强度正则，最少8位，最多20位，包括至少1个大写字母，1个小写字母，1个数字，1个特殊字符

### ISSUE THREAD

**Issue by jackwangwj** [any86/any-rule#56]
/^.*(?=.{8,20})(?=.*\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[!@#$%^&*?-_]).*$/

**Comment by any86** [comment]
感谢, 稍后更新, 如果有兴趣也可提pr

**Comment by any86** [comment]
今天看了下, 这个和我原有的密码强度正则相似度差不多, 所以暂时先不更新了, 问题也暂时不关闭, 看看到时候大家是想要我原来的那个"至少6位"还是要你的"8-20位", 最后我做下取舍
