### ISSUE TITLE
email地址匹配不准确

### ISSUE THREAD

**Issue by bltsheep** [any86/any-rule#6]
下列地址是合法的E-mail地址，但是无法验证通过：
wood@[123.123.13.3]
jsmith@[IPv6:2001:db8::1]
admin@mailserver1
" "@example.org
"john..doe"@example.org

见 https://en.wikipedia.org/wiki/Email_address
https://tools.ietf.org/html/rfc5321#section-4.1.3

微软的文档中有一个好一些的正则，见 https://docs.microsoft.com/zh-cn/dotnet/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format

**Comment by any86** [comment]
好嘞, 多谢, 我研究下怎么改, 之前还真不知道这个格式. @bltsheep

**Comment by any86** [comment]
admin@mailserver1这个可以支持了.
其他的暂时还不支持, 我也试了淘宝和淘宝国际版的注册, 在输入邮箱的时候你列出的都不支持, 当然你列出的都是正确的邮箱格式,我看了你给的链接, 个人能力和时间的原因我先把这个ip和引号的支持延后处理, 见谅^_^  @bltsheep
