### ISSUE TITLE
我有更好的正则: 数字/货币金额（支持负数、千分位分隔符）

### ISSUE THREAD

**Issue by 52cik** [any86/any-rule#62]
`^-?\d+(,\d{3})*(\.\d{1,2})?$` 也能满足你的需求，原正则太啰嗦了。

**Comment by any86** [comment]
好的, 要不要加入一起玩, 最近时间有些紧张(20号左右就可以有时间了), 很期待有兴趣的朋友一起推进这个项目, 这几天刚新加入了一位朋友, 正在优化vscode的交互(已有了很大的体验优化). 我这边也有一个规划, 就是过年放假期间把项目改为多包管理的目录结构.

**Comment by any86** [comment]
真诚的邀请你加入,(*^▽^*)

**Comment by 52cik** [comment]
插件没搞过，但可以试试。

**Comment by any86** [comment]
可以先改你说的这些正则, 这些是核心, 我先拉你进组

**Comment by 52cik** [comment]
好的

**Comment by any86** [comment]
https://github.com/any86/any-rule/invitations

**Comment by any86** [comment]
正则都在这里=> packages/www/src/RULES.js

欢迎加入

**Comment by 52cik** [comment]
改完了，怎么发布？

**Comment by any86** [comment]
在哪个分支? 我没有看到啊

**Comment by 52cik** [comment]
发布好了，你看看。

**Comment by any86** [comment]
好的, 下次请提交到develop分支, 再就是提交信息github有个小技巧, 比如可以这么写:  "fix: 精简xx正则长度 (#59)"
这里59是对应的issue, 这样issue会自动关联你的issue.

**Comment by any86** [comment]
辛苦啦^_^

**Comment by 52cik** [comment]
好的
