### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by Gavin-Chu** [any86/any-rule#65]
需求: 按 ;(分号)分割字符串,但不包括 被单双引号包裹的;(分号)

**Comment by 52cik** [comment]
能提供几个测试数据吗？
以及你最终想得到的结果数据。
如果有特殊情况不要匹配的，也说明下，没有就不用说明。

**Comment by Gavin-Chu** [comment]
这是源串: 
	
IF EXISTS (select top 1 OTP_Station from OperatorTermProfile
where OTP_OperatorNO=0  AND OTP_Station=0 AND OTP_TerminalType= '0' )
BEGIN
   update OperatorTermProfile set OTP_OperatorProfile = '{"name":"hello world;weqwe"}'
   where OTP_OperatorNO=0  and OTP_Station=0 and OTP_TerminalType= '0'
END ELSE BEGIN
  insert into OperatorTermProfile (OTP_Station,OTP_OperatorNO,OTP_TerminalType,OTP_OperatorProfile)
  values (0,0,'0','{"name":"hello world;weqwe"}')
END;IF EXISTS (select top 1 OTP_Station from OperatorTermProfile
where OTP_OperatorNO=0  AND OTP_Station=0 AND OTP_TerminalType= '0' )
BEGIN
   update OperatorTermProfile set OTP_OperatorProfile = '{"name":"hello world;weqwe"}'
   where OTP_OperatorNO=0  and OTP_Station=0 and OTP_TerminalType= '0'
END ELSE BEGIN
  insert into OperatorTermProfile (OTP_Station,OTP_OperatorNO,OTP_TerminalType,OTP_OperatorProfile)
  values (0,0,'0','{"name":"hello world;weqwe"}')
END
想要生成这种：
 ["IF EXISTS (select top 1 OTP_Station from OperatorTermProfile
where OTP_OperatorNO=0  AND OTP_Station=0 AND OTP_TerminalType= '0' )
BEGIN
   update OperatorTermProfile set OTP_OperatorProfile = '{"name":"hello world;weqwe"}'
   where OTP_OperatorNO=0  and OTP_Station=0 and OTP_TerminalType= '0'
END ELSE BEGIN
  insert into OperatorTermProfile (OTP_Station,OTP_OperatorNO,OTP_TerminalType,OTP_OperatorProfile)
  values (0,0,'0','{"name":"hello world;weqwe"}')
END", "IF EXISTS (select top 1 OTP_Station from OperatorTermProfile
where OTP_OperatorNO=0  AND OTP_Station=0 AND OTP_TerminalType= '0' )
BEGIN
   update OperatorTermProfile set OTP_OperatorProfile = '{"name":"hello world;weqwe"}'
   where OTP_OperatorNO=0  and OTP_Station=0 and OTP_TerminalType= '0'
END ELSE BEGIN
  insert into OperatorTermProfile (OTP_Station,OTP_OperatorNO,OTP_TerminalType,OTP_OperatorProfile)
  values (0,0,'0','{"name":"hello world;weqwe"}')
END"]

**Comment by 52cik** [comment]
吃午饭，稍等。

**Comment by Gavin-Chu** [comment]
好的，膜拜大佬

**Comment by 52cik** [comment]
刚刚看了下，这个问题比较麻烦，如果简单处理，直接用 `END;` 关键词分割即可，但用户输入的字符串包含 END; 就蛋疼了。
所以如果要精确处理，需要3步。
1. 提取带 ; 的字符串，然后写个占位符
2. 按 ; 分割
3. 把字符串替换回去

你看看简单处理是否符合你的需求，如果不行，我再写个精确处理的 demo

**Comment by Gavin-Chu** [comment]
需要精确的，使用软件的用户年龄偏大的，麻烦你了

**Comment by 52cik** [comment]
年龄偏大会在输入框里写 END; 这么精确的字符串？？

**Comment by Gavin-Chu** [comment]
那大佬先写个简单的正则我套用一下看看效果，后期有需要再找你讨论

**Comment by 52cik** [comment]
```js
let str = `IF EXISTS (select top 1 OTP_Station from OperatorTermProfile
where OTP_OperatorNO=0 AND OTP_Station=0 AND OTP_TerminalType= '0' )
BEGIN
update OperatorTermProfile set OTP_OperatorProfile = '{"name":"hello world;weqwe"}'
where OTP_OperatorNO=0 and OTP_Station=0 and OTP_TerminalType= '0'
END ELSE BEGIN
insert into OperatorTermProfile (OTP_Station,OTP_OperatorNO,OTP_TerminalType,OTP_OperatorProfile)
values (0,0,'0','{"name":"hello world;weqwe"}')
END;IF EXISTS (select top 1 OTP_Station from OperatorTermProfile
where OTP_OperatorNO=0 AND OTP_Station=0 AND OTP_TerminalType= '0' )
BEGIN
update OperatorTermProfile set OTP_OperatorProfile = '{"name":"hello world;weqwe"}'
where OTP_OperatorNO=0 and OTP_Station=0 and OTP_TerminalType= '0'
END ELSE BEGIN
insert into OperatorTermProfile (OTP_Station,OTP_OperatorNO,OTP_TerminalType,OTP_OperatorProfile)
values (0,0,'0','{"name":"hello world;weqEND;we"}')
END`;

let arr = str.replace(/"(?:\\.|[^"])*"/g, (m) => {
  return m.replace(/END;/g, '\0END\0'); // 把字符串中的关键词替换掉
}).split('END;'); // 按 END; 分割

arr = arr.map((it, idx) => {
  if (idx !== arr.length - 1) {
    it += 'END;'; // 除了最后一个，都补上分隔符
  }
  return it.replace(/\0END\0/g, 'END;'); // 占位符替换回来
});

console.log(arr);
```

输出

```js
[ 'IF EXISTS (select top 1 OTP_Station from OperatorTermProfile\nwhere OTP_OperatorNO=0 AND OTP_Station=0 AND OTP_TerminalType= \'0\' )\nBEGIN\nupdate OperatorTermProfile set OTP_OperatorProfile = \'{"name":"hello world;weqwe"}\'\nwhere OTP_OperatorNO=0 and OTP_Station=0 and OTP_TerminalType= \'0\'\nEND ELSE BEGIN\ninsert into OperatorTermProfile (OTP_Station,OTP_OperatorNO,OTP_TerminalType,OTP_OperatorProfile)\nvalues (0,0,\'0\',\'{"name":"hello world;weqwe"}\')\nEND;',
  'IF EXISTS (select top 1 OTP_Station from OperatorTermProfile\nwhere OTP_OperatorNO=0 AND OTP_Station=0 AND OTP_TerminalType= \'0\' )\nBEGIN\nupdate OperatorTermProfile set OTP_OperatorProfile = \'{"name":"hello world;weqwe"}\'\nwhere OTP_OperatorNO=0 and OTP_Station=0 and OTP_TerminalType= \'0\'\nEND ELSE BEGIN\ninsert into OperatorTermProfile (OTP_Station,OTP_OperatorNO,OTP_TerminalType,OTP_OperatorProfile)\nvalues (0,0,\'0\',\'{"name":"hello world;weqEND;we"}\')\nEND' ]
```

**Comment by Gavin-Chu** [comment]
THK

**Comment by Gavin-Chu** [comment]
发现用END关键词去处理不行，如果换成了其他的数据就要重新去改，我发的例子误导了你。需求还是这个，除了被单双引号包裹的;(分号)，其他的;(分号)都分割字符串，看能做成一行代码就能处理的正则表达式不

**Comment by any86** [comment]
请提供一个最小化的字符串用例 @Gavin-Chu

**Comment by Gavin-Chu** [comment]
abc;abc(0,'0','{"name":"hello world;abc"}')abc;abc(0,'0','{"name":"hello world;abc"}')abc    类似这种
就是遇见分号就分割为字符串，但是单双引号包住的分号就不要分割，我是表达有啥问题吗

**Comment by any86** [comment]
@Gavin-Chu 我只想了解下实际的业务中的字符串是什么样子的, 业务还能有别的"特征"可以使用, 实际中的"双引号"是只会出现在"**{}**" 内部吗?
