### ISSUE TITLE
我有更好的正则: 密码强度校验，最少6位，包括至少1个大写字母，1个小写字母，1个数字，1个特殊字符

### ISSUE THREAD

**Issue by kuailelp** [any86/any-rule#66]
^(?=.*?[A-Z])(?=(.*[a-z]){1,})(?=(.*[\d]){1,})(?=(.*[\W]){1,})(?!.*\s).{8,}$

这个正则表达式将强制执行这些规则：
由于特殊字符仅限于键盘中的特殊字符，因此可用于任何特殊字符：
– 至少1个大写英文字母
– 至少1个小写英文字母
– 至少1位数字
– 至少1个特殊字符
– 最少8个长度

**Comment by any86** [comment]
感谢, 最近比较忙, 稍后放假同步

**Comment by 52cik** [comment]
你这个有测试过吗？
我根据你的描述重写了个，你可以试试。
`/^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[\W_]).{8,}$/`
