### ISSUE TITLE
我有更好的正则: 邮箱地址(email)

### ISSUE THREAD

**Issue by szkzn** [any86/any-rule#69]
您好，说明一点遗漏的校验

域名部分的校验：
根据域名rfc定义，不允许以连字符 - 开头和结尾，不允许连字符连续在域名出现，连字符每次出现最多允许出现1次，如1--2.cn,4fjs---aj.3.cn，1-2.3--a.db.cc
允许连字符不连续出现,如下面是允许的，
a-3.djs.lko-s.dh-1-1-j-h.cv

最后如下：
@前面部分我没什么异议，RFC规范定义很复杂，真按rfc规范走，邮箱长度可以支持到256位，支持中文/其他语种/语言，可能得几十行都写不完

谨慎的为@后面的域名部分做点补充，可以仅看@后面的
^w+([-+.]w+)@w+([-.]w+).w+([-.]w+)

其他：xxx@前面xxx部分，这个真的不好说，很多邮箱服务端的事实标准很复杂（商业因素），被人为限制长度上限和下限，限制允许使用的特殊字符，我这里没什么好的建议，保持不变，等待别人去补充吧

**Comment by any86** [comment]
rfc那个之前有位也提过, 太过复杂了, 好像还有一些特殊符号是允许包括的, 开眼界了, 本想着有时间去自己研究下, 不过单位一直忙,现在还在居家上班事件不允许那么极致啊...😆

**Comment by any86** [comment]
上面忘记感谢了, 嘿嘿

**Comment by any86** [comment]
我一会看下@后面
