### ISSUE TITLE
补充一个不常用的

### ISSUE THREAD

**Issue by chenyunxuan** [any86/any-rule#7]
1.   /^([1-9]\d|[1-9])(\.([1-9]\d|\d)){2}$/ 版本号格式必须为X.Y.Z且首位不可为0,用于app后台录入

**Comment by any86** [comment]
太有用了, 十分感谢,有个疑问, 为啥限制首位不能为0?

**Comment by any86** [comment]
我给改了下 @chenyunxuan 
/^\d{1,}(\.([1-9]\d|\d)){2}$/

**Comment by any86** [comment]
.前面的转义斜杠被github过滤了, 我说你的怎么少个斜杠

**Comment by chenyunxuan** [comment]
app版本号规则就是从1.0.0迭代的,所以规定开头不能以0打头

**Comment by chenyunxuan** [comment]
如果特殊要求可以改.我也是自己公司用,尝试的,哈哈

**Comment by any86** [comment]
嘿嘿, 我为了通用, 我就给改成成可以0开头了, 感谢对"正则大全"做出的贡献

**Comment by MrTenger** [comment]
我说呲溜呲溜的收到邮件，热闹起来了，受教了受教了
