### ISSUE TITLE
vscode 插件搜索正则问题

### ISSUE THREAD

**Issue by shoyuf** [any86/any-rule#70]
搜索 `>zz: 手机` 只能搜索到手机机身码，`中国手机号`等无法显示出来
![截屏2020-02-19下午12 42 08](https://user-images.githubusercontent.com/27998490/74802798-dae3c400-5315-11ea-8f36-b4edaca2965b.png)

**Comment by any86** [comment]
感谢反馈, 这个功能使用了vscode控件, 控件不支持分词搜索, 我已经"新增"了一种查询方式, 稍后发版,正在测试中.

**Comment by any86** [comment]
由于在vscode中插件只能使用vscode的组件, 受限于组件没法实现"分词"搜索, 但是新版增加了一种触发方式:
新版本增加任意文件位置输入"zz."触发弹出列表.  这样就可以不用输入"zz", 更符合直接输入关键词的直觉反应. 欢迎更新使用.

[新增方法](https://github.com/any86/any-rule#%E4%BD%BF%E7%94%A8)
