### ISSUE TITLE
身份证号匹配会匹配到15个0的情况

### ISSUE THREAD

**Issue by YuanjianZhang** [any86/any-rule#78]
https://github.com/any86/any-rule/blame/master/README.md#L267  
https://github.com/any86/any-rule/blame/master/README.md#L277  
我遇到个问题，这两个正则会匹配000000000000000  
我应该如何处理它？

**Comment by any86** [comment]
感谢反馈, 我研究下相关文档, 看看还有什么规则可以约束

**Comment by any86** [comment]
下次发版更新到vscode中, 感谢你为any-rule做出的贡献^_^
