### ISSUE TITLE
银行卡号长度

### ISSUE THREAD

**Issue by Sinosaurus** [any86/any-rule#8]
北京银行的卡号 24位，虽然很特殊，确实是如此的，校验规则需要改下

**Comment by MrTenger** [comment]
@Sinosaurus 我擦，现在北京银行都是24位啦？稍等，我去找找我的北京银行卡

**Comment by MrTenger** [comment]
@Sinosaurus 特意去支付宝和微信绑卡界面看了一下，两者还有所不同
 - 微信绑卡最多支持输入 `21`位
- 支付宝绑卡最多支持输入 `19`位

我看了我的也没有这么多位，那可能24位的卡是新出的吧，这样支付宝和微信也要修改了哈哈，老哥威武！

![zfb](https://user-images.githubusercontent.com/10781715/60960793-5374b200-a33d-11e9-9f1a-de9018c7b3c8.png)
![wx](https://user-images.githubusercontent.com/10781715/60960794-540d4880-a33d-11e9-9432-9922f1069382.png)

**Comment by Sinosaurus** [comment]
厉害了，这个是一个客户提出来的，我当时是19位，然后问了下客户，他是北京银行卡，`24位`，我也是一脸无奈

**Comment by gaoqiang19514** [comment]
牛皮，我前几天还特地百度了下，好像没有超过19位的，百度上有几个人说有20位的，但是感觉不可信，没想到还有24位的，惊了！

**Comment by any86** [comment]
@MrTenger 商量下, 咱到底要不要给开24位呢?

**Comment by any86** [comment]
@MrTenger 商量下, 咱到底要不要给开24位呢?  能确定有24位的卡吗?

**Comment by MrTenger** [comment]
@any86 再考证一下 确实罕见呐

**Comment by gaoqiang19514** [comment]
> @any86 再考证一下 确实罕见呐

他说是北京银行，直接找背景银行的客服确认下吧

**Comment by any86** [comment]
@gaoqiang19514  午休的

**Comment by Sinosaurus** [comment]
我刚打了北京银行客服，说是只有 `16` 和 `19`位，但是我同事说他同学问他北京银行是否有`24`位，看样子不是我一个人碰到

**Comment by any86** [comment]
24这个真的不确定有没有 暂时先不加了 但是如果你单位要求你就加一个, 我给你改好了:
```javascript
/^([1-9]{1})(\d{15}|\d{18}|\d{23})$/
```

**Comment by Sinosaurus** [comment]
https://kf.qq.com/faq/170112ABnm6b170112FvquAn.html，
新消息，对公卡号是不一样的，我朋友公司对公账号 **12位**

**Comment by any86** [comment]
@Sinosaurus 这个问题还真的需要讨论下, 这个issue我重开, 现在关注这个项目人多了, 看看大家都说什么.

**Comment by phantomk** [comment]
这是一份微信支付的开户银行对照表

银行名 | 卡格式 | 对私卡号长度 | 对公账户长度
-- | -- | -- | --
工商银行 | 数字、符号- | 16\|17\|18\|19 | 16\|19\|26\|29
交通银行 | 数字 | 16\|17\|18\|19\|21 | 8\|18\|20\|21\|24\|27
招商银行 | 数字 | 10\|12\|15\|16 | 13\|15\|16\|17\|18\|19\|20\|21
民生银行 | 数字 | 12\|16 | 9\|15\|16\|20
中信银行 | 数字 | 16\|19 | 19
浦发银行 | 数字 | 12\|16 | 13\|14\|15\|16\|17\|18\|19\|20\|23
兴业银行 | 数字 | 16\|18 | 17\|18\|22\|24
光大银行 | 数字 | 16\|17 | 17\|21\|22\|23\|24\|25\|26\|27\|28\|29\|30
广发银行 | 数字 | 16\|18\|19 | 15\|17\|18\|19\|20\|23\|24\|25
平安银行 | 数字 | 11\|13\|14\|16\|19 | 13\|14\|18
北京银行 | 数字 | 16\|13 | 21\|23\|28
华夏银行 | 数字 | 16 | 16\|17\|22
农业银行 | 数字 | 16\|18\|19 | 17\|19\|27
建设银行 | 数字 | 16\|17\|18\|19\|20 | 16\|19\|20\|24\|25\|26\|27
邮政储蓄银行 | 数字 | 14\|18\|19 | 16\|18\|23
中国银行 | 数字、符号- | 12\|16\|18\|19 | 12\|18\|19
宁波银行 | 数字 | 16\|17\|19 | 16\|17\|19\|23
其他银行 | 数字 | 30位以内 | 30位以内
