### ISSUE TITLE
有数据接口吗？

### ISSUE THREAD

**Issue by zhoriya** [any86/any-rule#82]
如题，本人在开发基于idea全家桶的插件，请问下是否有数据查询接口？如果没有的话就做成全静态的了

**Comment by any86** [comment]
感谢终于有小伙伴要做idea版本了😊

暂时没有哦, 稍后我整理下项目结构, 会把这个文件发布到npm给开发者用.
https://github.com/any86/any-rule/blob/master/packages/www/src/RULES.js

**Comment by any86** [comment]
我想下服务器的问题怎么解决, 找个机会放到服务器上, 现在vscode版本不放是因为最早的交互是通过命令选择正则, 那个api需要正则文件是本地的(历史包袱了), 新开发的调用方式已经可以一步加载了, 现在就是等机会

**Comment by zhoriya** [comment]
> 我想下服务器的问题怎么解决, 找个机会放到服务器上, 现在vscode版本不放是因为最早的交互是通过命令选择正则, 那个api需要正则文件是本地的(历史包袱了), 新开发的调用方式已经可以异步加载了, 现在就是等机会

嗯，了解

**Comment by zhoriya** [comment]
> 感谢终于有小伙伴要做idea版本了😊
> 
> 暂时没有哦, 稍后我整理下项目结构, 会把这个文件发布到npm给开发者用.
> https://github.com/any86/any-rule/blob/master/packages/www/src/RULES.js

想请问下vscode插件的数据是怎么来，可以提供下吗，因为RULE.js文件需要清理一下才能使用，挺麻烦的，如果有现成的话就方便许多了

**Comment by any86** [comment]
我用的就是这个啊, 可以自己遍历一下嘛

**Comment by zhoriya** [comment]
> 我用的就是这个啊, 可以自己遍历一下嘛

https://raw.githubusercontent.com/any86/any-rule/master/packages/www/src/RULES.js
主要是这个原始地址突然失效了，没法玩

**Comment by zhoriya** [comment]
> 我用的就是这个啊, 可以自己遍历一下嘛



[any-rule.zip](https://github.com/any86/any-rule/files/4491516/any-rule.zip)
@any86 做了个基本的雏形出来，看一下效果如何
鼠标右键使用

**Comment by any86** [comment]
在界面哪里能找到, 我本机没有idea, 我找别人机器试试

**Comment by zhoriya** [comment]
> 👍 在界面哪里能找到功能, 我本机没有idea, 我找别人机器试试


文本编辑页面，然后右键使用，这githup网络有问题，一直上传了不了图片

**Comment by any86** [comment]
我找别人电脑试了下idea,, 基本没啥问题,  我不用idea, 所以我也不会研究他的插件开发, 要不你单独开个仓库, 然后给我github地址, 然后我在首页给你做链接.

**Comment by zhoriya** [comment]
> 我找别人电脑试了下idea,, 基本没啥问题, 我不用idea, 所以我也不会研究他的插件开发, 要不你单独开个仓库, 然后给我github地址, 然后我在首页给你做链接.

嗯，代码整理后会上传githup的，你vscode用的是哪个键盘快捷键，我也要绑定个快捷键

**Comment by any86** [comment]
我的没有指定快捷键, 正则我都融入了系统功能的列表, 系统功能列表默认快捷键F1,  
我还有2中方式:
1. 右键菜单
2. 文本任意位置输入"@zz" 可唤起正则列表

**Comment by zhoriya** [comment]
> 我找别人电脑试了下idea,, 基本没啥问题, 我不用idea, 所以我也不会研究他的插件开发, 要不你单独开个仓库, 然后给我github地址, 然后我在首页给你做链接.

可以啦   [插件仓库地址](https://github.com/zhoriya/idea-rule)

**Comment by any86** [comment]
好嘞, 加到首页置顶了.

**Comment by any86** [comment]
发沸点了, 给你带带star

https://juejin.im/pin/5e9f9518e51d451a6532f40e

**Comment by zhoriya** [comment]
先不急，idea插件市场还没上架呢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "any86"<notifications@github.com&gt;; 
发送时间: 2020年4月22日(星期三) 上午9:33
收件人: "any86/any-rule"<any-rule@noreply.github.com&gt;; 
抄送: "周佳"<1171935932@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [any86/any-rule] 有数据接口吗？ (#82)





 
发沸点了, 给你带带star
 
https://juejin.im/pin/5e9f9518e51d451a6532f40e

**Comment by zhoriya** [comment]
> 发沸点了, 给你带带star
> 
> https://juejin.im/pin/5e9f9518e51d451a6532f40e

插件终于上架了
