### ISSUE TITLE
[vscode feedback] 中文/汉字

### ISSUE THREAD

**Issue by dbsxdbsx** [any86/any-rule#84]
想在vscode 通过 `/^(?:[\u3400-\u4DB5\u4E00-\u9FEA\uFA0E\uFA0F\uFA11\uFA13\uFA14\uFA1F\uFA21\uFA23\uFA24\uFA27-\uFA29]|[\uD840-\uD868\uD86A-\uD86C\uD86F-\uD872\uD874-\uD879][\uDC00-\uDFFF]|\uD869[\uDC00-\uDED6\uDF00-\uDFFF]|\uD86D[\uDC00-\uDF34\uDF40-\uDFFF]|\uD86E[\uDC00-\uDC1D\uDC20-\uDFFF]|\uD873[\uDC00-\uDEA1\uDEB0-\uDFFF]|\uD87A[\uDC00-\uDFE0])+$/ ` 来批量替换汉字，但好像找不到（已勾选正则查找）,我猜测原因应该是vs的正则格式和一般正则格式还是有点区别的。 希望能够添加转换，谢谢

**Comment by any86** [comment]
我试了下, 太长的正则vscode保存, 你先试试这个`\p{Unified_Ideograph}{1,2}`

**Comment by any86** [comment]
据我观察vscode的正则应该就是普通js正则

**Comment by dbsxdbsx** [comment]
@any86 ,谢谢，你这个可行。就是不会整行汉字选中...

**Comment by any86** [comment]
把后面的{1,2}改下啊, 我只是举例🌰

**Comment by dbsxdbsx** [comment]
@any86 ，OK
