### ISSUE TITLE
合法的身份证校验不过

### ISSUE THREAD

**Issue by gaoqiang19514** [any86/any-rule#9]
440307198810281422
老哥看看

**Comment by any86** [comment]
@gaoqiang19514 改完咯, 我的是错误, 月份没有匹配10月, 漏匹配了一个0, sorry

**Comment by gaoqiang19514** [comment]
我昨天用到生产了。。。
![我掐死你](http://ww3.sinaimg.cn/large/6af89bc8gw1f8ub4lgesbj203c02tdfw.jpg)

**Comment by any86** [comment]
@gaoqiang19514 实在抱歉, 现在的还有问题吗?

**Comment by gaoqiang19514** [comment]
现在没问题了
